Update check-pr-files-template.yml

diff --git a/workflow-templates/check-pr-files-template.yml b/workflow-templates/check-pr-files-template.yml
--- a/workflow-templates/check-pr-files-template.yml
+++ b/workflow-templates/check-pr-files-template.yml
@@ -7,21 +7,47 @@ description: >
 
 on:
   pull_request:
-    types: [opened, synchronize]
+    branches:
+      - main
 
 jobs:
-  check_pr_files:
+  count_changed_files:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Install GitHub CLI
-        run: sudo apt-get install gh
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 1000
+
+      - name: Fetch main branch
+        run: git fetch origin main
 
       - name: Count changed files
-        id: file_count
+        id: count
         run: |
-          PR_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files | length')
-          echo "PR_FILES=$PR_FILES" >> $GITHUB_ENV
+          # Get the number of changed files
+          FILES_CHANGED=$(git diff --name-only origin/main... | wc -l)
+          echo "Changed files: $FILES_CHANGED"
+          
+          # Set the output variable
+          echo "PR_FILES=$FILES_CHANGED" >> $GITHUB_ENV
+      
+      - name: Post a comment if PR exceeds 15 files
+        env:
+          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
+        if: env.PR_FILES > 15
+        run: |
+          gh pr comment ${{ github.event.pull_request.number }} --body "This PR contains **${{ env.PR_FILES }}** files, which is more than the allowed limit of 15 files. Please split it into smaller PRs for easier review."
+
+
+      - name: Fail if more than 15 files changed
+        run: |
+          if [ ${{ env.PR_FILES }} -gt 15 ]; then
+            echo "Error: More than 15 files changed in this PR. Please limit to 15 files or fewer."
+            exit 1
+          fi
 
       - name: Post a comment if PR exceeds 15 files
         if: env.PR_FILES > 15
